### PR TITLE
test: enable tests to run on kokoro

### PR DESCRIPTION
**Pull request by skuruppu**

### CODE REVIEW

**Comment by skuruppu** [comment]
@larkee or @IlyaFaer I'm trying to get the tests running on Kokoro. But as you can see above, the run fails with errors like:

```
____________________ ERROR at setup of test_get_table_names ____________________
Traceback (most recent call last):
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/snippets/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/snippets/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/snippets/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Instance not found: projects/precise-truck-742/instances/sqlalchemy-dialect-test"
	debug_error_string = "{"created":"@1634185605.444094995","description":"Error received from peer ipv4:74.125.142.95:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Instance not found: projects/precise-truck-742/instances/sqlalchemy-dialect-test","grpc_status":5}"
```

But you can see in the logs that `nox > python create_test_database.py` is executed without error. So I'm not quite sure why the tests are not able to find the instance.

@larkee I don't have permission on that project to see the instances.

**Comment by skuruppu** [comment]
@IlyaFaer would you please be able to take a look at the 3 snippets test failures [here](https://fusion2.corp.google.com/invocations/a3ba791e-eaa9-41ad-974c-2dfa3fabb668/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner-sqlalchemy%2Fpresubmit%2Fpresubmit;config=default/log)?

**Comment by skuruppu** [comment]
Thanks for the review @larkee. PTAL

I addressed your feedback except for the one about creating a base class for setting up the engine. @IlyaFaer if this is something that you can do, then I'm happy for you to do so in a separate PR.

**Comment by IlyaFaer** [comment]
@skuruppu, okay, created an issue not to forget: https://github.com/googleapis/python-spanner-sqlalchemy/issues/138
Will do.

**Review by larkee — APPROVED** [review]

**Pull request merged**
