### PR TITLE
feat: support JSON data type

### PR DESCRIPTION
**Pull request by IlyaFaer**
Based on another PR: https://github.com/googleapis/python-spanner/pull/627

### CODE REVIEW

**Comment by skuruppu** [comment]
Yeah JSON is not available in the emulator yet AFAIK.

**Comment by skuruppu** [comment]
@IlyaFaer will you be able to take a look at the Kokoro failures?

Also, please skip the JSON tests when being run against the emulator. We don't yet have an ETA for when the emulator will support JSON.

**Comment by IlyaFaer** [comment]
@skuruppu, of course, I'm actually working on those failures, just a little bit stuck with strange errors.

**Comment by IlyaFaer** [comment]
@skuruppu, looks like everything is okay now.

I guess we should release the `python-spanner` with all the JSON-related changes and then update the dependencies here, in the dialect code. To make sure the dialect uses the `python-spanner` version with all the necessary changes.

**Comment by skuruppu** [comment]
Thanks a lot @IlyaFaer for the fixes. We're in a release freeze right now due to the public holidays in the US. But we should be able to release the Python client on 1st Dec and then we can update the dependency here.

@larkee this is now ready for review.

**Review by larkee — COMMENTED** [review]
LGTM but I'd like to wait on the client release next week to confirm this works as intended against prod

**Comment by skuruppu** [comment]
@IlyaFaer would you please be able to take a look at the compliance test failure?

**Review by larkee — APPROVED** [review]

**Pull request merged**
