### PR TITLE
test: run snippets tests on Kokoro

### PR DESCRIPTION
**Pull request by skuruppu**

### CODE REVIEW

**Comment by skuruppu** [comment]
The snippets test did succeed, but one of the transactions was aborted in the compliance test so I'm rerunning it now.

**Review by larkee — COMMENTED** [review]
If they must be run against production then we should leave the `GOOGLE_APPLICATION_CREDENTIALS` check in.

**Comment by skuruppu** [comment]
> If they must be run against production then we should leave the `GOOGLE_APPLICATION_CREDENTIALS` check in.

Ah right but it turns out that Kokoro doesn't set up that variable. We were only doing that in CircleCI so the tests kept getting skipped on Kokoro. This now makes the tests run on Kokoro.

**Comment by larkee** [comment]
> > If they must be run against production then we should leave the `GOOGLE_APPLICATION_CREDENTIALS` check in.
> 
> Ah right but it turns out that Kokoro doesn't set up that variable. We were only doing that in CircleCI so the tests kept getting skipped on Kokoro. This now makes the tests run on Kokoro.

Hmmm, how strange.. In that case, LGTM :+1:

**Review by larkee — APPROVED** [review]

**Pull request merged**
